apiVersion: v2
name: platform-neuro-flow
description: Neu.ro flow service
version: 1.2.1
appVersion: 1.0.0
dependencies:
  - name: postgres-db-init
    version: "1.2.19"
    repository: https://neuro-inc.github.io/helm-charts
